version: '3'
services:
  exec-db:
    image: mongo:latest
    ports:
      - "27000:27017"
    volumes:
      - "execdb-data:/data/db"
#This needs to be containerized
  exec-db-setup:
    build: exec-db
    depends_on:
      - exec-db

  exec-ui:
    image: sredna/hygieia-exec-ui
    ports:
      - "4200:80"
    depends_on:
      - exec-db-setup
    environment:
      - API_URL=http://exec-api:8080

  exec-api:
    image: sredna/hygieia-exec-api
    build:
      context: exec-api
      args:
        JAR_FILE: "./api-target/exec-api*.jar"
    volumes:
      - "./config/api:/var/app/config"
    depends_on:
      - exec-db-setup

  exec-analysis:
    image: sredna/hygieia-exec-analysis
    build:
      context: exec-analysis
      args:
        JAR_FILE: "./analysis-target/exec-analysis*.jar"
    volumes:
      - "./config/analysis:/var/app/config"

volumes: 
  execdb-data:

networks:
  default:
    external:
      name: hygieia_default
