# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:

  packagejs:
    docker:
      # specify the version you desire here
      - image: circleci/node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: mkdir -p node-target && mkdir -p /tmp/workspace/ && cp -r node-target /tmp/workspace && cp Dockerfile /tmp/workspace/node-target/
      - persist_to_workspace:
          root: /tmp/workspace/node-target
          paths:
            - ./*
            - ./Dockerfile
  package:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m 

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn -s .circleci/.circleci.settings.xml clean package -DskipTests
      #Why save the cache twice?  In case the mvn test didn't pull everything correctly, we have a second go.
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: pwd
      - run: ls -al
      - run: mkdir -p /tmp/workspace/exec-analysis && mkdir -p /tmp/workspace/exec-api && mkdir -p /tmp/workspace/exec-core
      - run: cp -r exec-analysis/target/. /tmp/workspace/exec-analysis && cp exec-analysis/Dockerfile /tmp/workspace/exec-analysis
      - run: cp -r exec-api/target/. /tmp/workspace/exec-api && cp exec-api/Dockerfile /tmp/workspace/exec-api
      - run: cp -r exec-core/target/. /tmp/workspace/exec-core && cp exec-core/Dockerfile /tmp/workspace/exec-core
      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - ./*
            - ./*.jar
            - ./Dockerfile
  lint:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd exec-ui
      - run: npm run lint

  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m 
    steps:
      - checkout    
      # Download and cache dependencies
      - run: mvn -s .circleci/.circleci.settings.xml clean test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit/
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: VERSION_NUM=($CIRCLE_BUILD_NUM + 1) && sed -i "s/BUILDNUMBER/$VERSION_NUM/g" pom.xml
      - run: VERSION_NUM=($CIRCLE_BUILD_NUM + 1) && sed -i "s/BUILDNUMBER/$VERSION_NUM/g" exec-analysis/pom.xml
      - run: VERSION_NUM=($CIRCLE_BUILD_NUM + 1) && sed -i "s/BUILDNUMBER/$VERSION_NUM/g" exec-api/pom.xml
      - run: VERSION_NUM=($CIRCLE_BUILD_NUM + 1) && sed -i "s/BUILDNUMBER/$VERSION_NUM/g" exec-core/pom.xml
      - run: mvn -s .circleci/.circleci.settings.xml deploy -DskipTests
  publish_exec_analysis:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace/exec-analysis
      - run: ls -lart /tmp/workspace/exec-analysis/target
      - run: mkdir analysis-target && mv /tmp/workspace/exec-analysis/target/exec-analysis-*.jar analysis-target/exec-analysis.jar && mv /tmp/workspace/exec-analysis/Dockerfile ./Dockerfile
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t sredna/hygieia-exec-analysis:$TAG .
          docker tag sredna/hygieia-exec-analysis:$TAG sredna/hygieia-exec-analysis:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sredna/hygieia-exec-analysis:$TAG
          docker push sredna/hygieia-exec-analysis:latest
  publish_exec_core:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace/exec-core
      - run: ls -lart /tmp/workspace/exec-core/target
      - run: mkdir core-target && mv /tmp/workspace/exec-core/target/exec-core-*.jar core-target/exec-core.jar && mv /tmp/workspace/exec-core/Dockerfile ./Dockerfile
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t sredna/hygieia-exec-core:$TAG .
          docker tag sredna/hygieia-exec-core:$TAG sredna/hygieia-exec-core:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sredna/hygieia-exec-core:$TAG
          docker push sredna/hygieia-exec-core:latest
  publish_exec_api:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace/exec-api
      - run: ls -lart /tmp/workspace/exec-api/target
      - run: mkdir api-target && mv /tmp/workspace/exec-api/target/exec-api-*.jar api-target/exec-api.jar && mv /tmp/workspace/exec-api/Dockerfile ./Dockerfile
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t sredna/hygieia-exec-api:$TAG .
          docker tag sredna/hygieia-exec-api:$TAG sredna/hygieia-exec-api:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sredna/hygieia-exec-api:$TAG
          docker push sredna/hygieia-exec-api:latest
workflows:
  version: 2
  full_boat:
    jobs: 
      - lint
      - test
      - packagejs:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
      - package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - publish_exec_analysis:
          requires:
            - package
          filters:
            branches:
              only:
                - master
      - publish_exec_core:
          requires:
            - package
          filters:
            branches:
              only:
                - master
      - publish_exec_api:
          requires:
            - package
          filters:
            branches:
              only:
                - master